# Libraries

As in Python libraries can be used to give access to extra functionality.

**This this section we will import libraries and look at arrays.**

## SciPy

SciPy (pronounced “Sigh Pie”) is a Python-based ecosystem of open-source software for mathematics, science, and engineering.

The SciPy library is one of the core packages that make up the SciPy stack. It provides user-friendly and efficient numerical routines such as routines for numerical integration and optimization.

In [1]:
import scipy as sp

s = sp.randn(100)
print s[3]
print s[33]
print len(s)


1.74436512766
1.29109811334
100


In [2]:
print("Mean : {0:8.6f}".format(s.mean()))

Mean : 0.070828


## NumPy

Python does not have native support for arrays NumPy adds support for N-dimensional arrays.

In [3]:
import numpy as np

x = np.array([[42,47,11],[42,47,11]], int)
print x
x

[[42 47 11]
 [42 47 11]]


array([[42, 47, 11],
       [42, 47, 11]])